/**
 * Clauses & voice — P7 / S1 Scotland (CfE Second → Third Level).
 *
 * Fixed items with stable ids, so a wrong answer comes back as the *same*
 * item on review. Ids start at 101 so they cannot collide with the older
 * cl1…/pv1… bank in grammar.js.
 */

export const CLAUSE_VOICE_ITEMS = [
  /* ── Clauses ───────────────────────────────────────────────── */
  { id: 'cl101', topic: 'clauses',
    q: 'Which part of this sentence is the subordinate clause?\n\n"Because the loch had frozen, nobody took a boat out."',
    opts: ['Because the loch had frozen', 'nobody took a boat out', 'the loch had frozen', 'took a boat out'],
    a: 'Because the loch had frozen',
    hint: 'A subordinate clause starts with a joining word and cannot stand on its own.',
    ex: '"Because the loch had frozen" begins with the subordinating conjunction "because", so it depends on the main clause.' },

  { id: 'cl102', topic: 'clauses',
    q: 'Identify the main clause:\n\n"After Callum finished his homework, he walked the dog."',
    opts: ['he walked the dog', 'After Callum finished his homework', 'Callum finished his homework', 'After Callum'],
    a: 'he walked the dog',
    hint: 'The main clause would still make sense if you deleted everything else.',
    ex: '"He walked the dog" is a complete sentence by itself, so it is the main clause.' },

  { id: 'cl103', topic: 'clauses',
    q: 'Identify the subordinating conjunction:\n\n"Freya practised her lines until she knew them by heart."',
    opts: ['until', 'and', 'her', 'knew'],
    a: 'until',
    hint: 'Look for the word that hooks the second idea onto the first and makes it dependent.',
    ex: '"Until" introduces the subordinate clause "until she knew them by heart".' },

  { id: 'cl104', topic: 'clauses',
    q: 'Choose the correct relative pronoun:\n\n"The girl ___ scored the winning goal is in my class."',
    opts: ['who', 'which', 'whose', 'where'],
    a: 'who',
    hint: 'Think about whether the clause is about a person, a thing or a place.',
    ex: '"Who" is the relative pronoun for a person doing the action.' },

  { id: 'cl105', topic: 'clauses',
    q: 'Choose the correct relative pronoun:\n\n"Rory has a neighbour ___ dog barks all night."',
    opts: ['whose', 'who', 'which', "who's"],
    a: 'whose',
    hint: 'The dog belongs to the neighbour — which word shows belonging?',
    ex: '"Whose" shows possession and is followed straight away by the thing owned.' },

  { id: 'cl106', topic: 'clauses',
    q: 'Choose the correct relative pronoun:\n\n"The teacher ___ we met in Dundee has retired."',
    opts: ['whom', 'which', 'whose', 'what'],
    a: 'whom',
    hint: 'The person is not doing the meeting — the person is being met.',
    ex: '"Whom" is used when the person is the object of the verb: we met her.' },

  { id: 'cl107', topic: 'clauses',
    q: 'Choose the correct relative pronoun:\n\n"The bridge, ___ was built in 1890, is being repaired."',
    opts: ['which', 'that', 'who', 'whose'],
    a: 'which',
    hint: 'The commas tell you this is extra information about a thing.',
    ex: '"Which" introduces a non-defining clause about a thing; "that" can never follow a comma like this.' },

  { id: 'cl108', topic: 'clauses',
    q: 'Choose the correctly punctuated sentence.\n\n(The writer has only one sister.)',
    opts: ['My sister, who lives in Aviemore, is a ski instructor.',
      'My sister who lives in Aviemore, is a ski instructor.',
      'My sister, who lives in Aviemore is a ski instructor.',
      'My sister who lives in Aviemore is a ski instructor.'],
    a: 'My sister, who lives in Aviemore, is a ski instructor.',
    hint: 'If the clause is extra information, fence it off at both ends — like brackets.',
    ex: 'With only one sister, the clause is extra information, so it needs a comma on each side.' },

  { id: 'cl109', topic: 'clauses',
    q: 'Where should the comma go?\n\n"Although Skye is busy in summer it is quiet in winter."',
    opts: ['after "summer"', 'after "Although"', 'after "Skye"', 'after "quiet"'],
    a: 'after "summer"',
    hint: 'A subordinate clause placed at the front is closed off before the main clause starts.',
    ex: 'The fronted clause "Although Skye is busy in summer" ends there, so the comma marks the join.' },

  { id: 'cl110', topic: 'clauses',
    q: 'What type of sentence is this?\n\n"Euan cycled to school and Aisha took the bus."',
    opts: ['Compound', 'Simple', 'Complex', 'Compound-complex'],
    a: 'Compound',
    hint: 'Count the clauses, then check whether the joining word is a coordinating conjunction.',
    ex: 'Two main clauses joined by "and" make a compound sentence.' },

  { id: 'cl111', topic: 'clauses',
    q: 'What type of sentence is this?\n\n"The bus was late because the road was flooded."',
    opts: ['Complex', 'Simple', 'Compound', 'Compound-complex'],
    a: 'Complex',
    hint: 'One clause here cannot stand on its own.',
    ex: 'A main clause plus a subordinate clause beginning "because" makes a complex sentence.' },

  { id: 'cl112', topic: 'clauses',
    q: 'What type of sentence is this?\n\n"The pipers marched along the high street in the pouring rain."',
    opts: ['Simple', 'Compound', 'Complex', 'Compound-complex'],
    a: 'Simple',
    hint: 'Length is not the test — count the verbs.',
    ex: 'It is long, but it has only one clause and one verb group, so it is a simple sentence.' },

  { id: 'cl113', topic: 'clauses',
    q: 'Which part of this sentence is the embedded clause?\n\n"The path, which winds beside the loch, is slippery today."',
    opts: ['which winds beside the loch', 'The path is slippery today', 'is slippery today', 'beside the loch'],
    a: 'which winds beside the loch',
    hint: 'An embedded clause is dropped inside the main clause, often between a pair of commas.',
    ex: 'It sits inside the main clause "The path is slippery today" and is fenced off by commas.' },

  { id: 'cl114', topic: 'clauses',
    q: 'Choose the version with the subordinate clause moved to the front:\n\n"Aisha read her book while she waited for the train."',
    opts: ['While she waited for the train, Aisha read her book.',
      'While she waited for the train Aisha read her book.',
      'Aisha, while she waited for the train read her book.',
      'Aisha read her book, while she waited for the train.'],
    a: 'While she waited for the train, Aisha read her book.',
    hint: 'Fronting a subordinate clause changes the punctuation as well as the order.',
    ex: 'The subordinate clause comes first and a comma marks where the main clause begins.' },

  { id: 'cl115', topic: 'clauses',
    q: 'Which sentence contains a subordinate clause?',
    opts: ['Rory smiled when the sun finally appeared.',
      'Rory smiled and waved at the crowd.',
      'Rory smiled at the photographer.',
      'Rory smiled for the camera and then waved.'],
    a: 'Rory smiled when the sun finally appeared.',
    hint: 'Look for a word such as when, because, although or if.',
    ex: '"When the sun finally appeared" cannot stand alone, so it is a subordinate clause.' },

  { id: 'cl116', topic: 'clauses',
    q: 'What job does the relative clause do here?\n\n"The jacket that I left on the bus was brand new."',
    opts: ['It tells you which jacket is meant',
      'It adds extra information you could remove',
      'It joins two main clauses',
      'It replaces the main verb'],
    a: 'It tells you which jacket is meant',
    hint: 'Try deleting the clause and see whether you still know what is being talked about.',
    ex: 'It is a defining relative clause: it pins down which jacket, which is why it takes no commas.' },

  { id: 'cl117', topic: 'clauses',
    q: 'Is the relative clause defining or non-defining?\n\n"Mr Grant, who teaches us science, grew up in Oban."',
    opts: ['Non-defining', 'Defining', 'Neither — it is a main clause', 'Neither — it is a phrase'],
    a: 'Non-defining',
    hint: 'The punctuation is a strong clue, and so is the fact that he is already named.',
    ex: 'The commas show the clause is extra information, because his name already identifies him.' },

  { id: 'cl118', topic: 'clauses',
    q: 'Which sentence is missing a pair of commas?',
    opts: ['My gran who is eighty-two still swims in the sea.',
      'The boy who broke the window owned up.',
      'The book that I ordered has arrived.',
      'Anyone who wants a ticket should ask now.'],
    a: 'My gran who is eighty-two still swims in the sea.',
    hint: 'Only extra information needs commas — information that identifies does not.',
    ex: '"Who is eighty-two" is extra information about someone already identified, so it needs a comma at each end.' },

  { id: 'cl119', topic: 'clauses',
    q: 'Identify the subordinating conjunction:\n\n"If the ferry is cancelled, we will stay another night on Skye."',
    opts: ['If', 'will', 'another', 'we'],
    a: 'If',
    hint: 'Which word makes the first half unable to stand alone?',
    ex: '"If" introduces the subordinate clause "If the ferry is cancelled".' },

  { id: 'cl120', topic: 'clauses',
    q: 'Which word is NOT a subordinating conjunction?',
    opts: ['but', 'although', 'unless', 'whereas'],
    a: 'but',
    hint: 'One of these joins two clauses of equal weight rather than making one depend on the other.',
    ex: '"But" is a coordinating conjunction, so it links two main clauses instead of subordinating one.' },

  { id: 'cl121', topic: 'clauses',
    q: 'How many clauses does this sentence contain?\n\n"When the storm passed, Freya opened the window and the room filled with fresh air."',
    opts: ['Three', 'Two', 'Four', 'One'],
    a: 'Three',
    hint: 'Every clause has its own verb group — count them.',
    ex: 'The clauses are "When the storm passed", "Freya opened the window" and "the room filled with fresh air".' },

  { id: 'cl122', topic: 'clauses',
    q: 'Choose the correct relative word:\n\n"The village ___ we stayed is near Aviemore."',
    opts: ['where', 'which', 'who', 'whose'],
    a: 'where',
    hint: 'The clause tells you the place in which something happened.',
    ex: '"Where" links a relative clause to a place: the village where we stayed.' },

  { id: 'cl123', topic: 'clauses',
    q: 'Which sentence is complex?',
    opts: ['Callum missed the bus because he overslept.',
      'Callum missed the bus and walked to school.',
      'Callum missed the bus this morning.',
      'Callum missed the bus; he walked instead.'],
    a: 'Callum missed the bus because he overslept.',
    hint: 'A complex sentence needs a main clause and a subordinate clause.',
    ex: '"Because he overslept" is subordinate, so joining it to a main clause makes the sentence complex.' },

  { id: 'cl124', topic: 'clauses',
    q: 'Which sentence begins with a subordinate clause?',
    opts: ['Before the concert started, the hall was silent.',
      'The hall was silent before the concert started.',
      'In the hall, everyone was silent.',
      'The silent hall waited for the concert.'],
    a: 'Before the concert started, the hall was silent.',
    hint: 'A clause has its own verb; a phrase does not.',
    ex: '"Before the concert started" has its own verb and cannot stand alone, so it is a fronted subordinate clause.' },

  { id: 'cl125', topic: 'clauses',
    q: 'Choose the correct relative pronoun:\n\n"The photographs ___ Rory took of the glen won a prize."',
    opts: ['that', 'who', 'whom', 'whose'],
    a: 'that',
    hint: 'The clause is about things, and it tells you exactly which photographs.',
    ex: '"That" introduces a defining relative clause about things.' },

  { id: 'cl126', topic: 'clauses',
    q: 'Which sentence uses "whose" correctly?',
    opts: ['We met a farmer whose sheepdog had won a medal.',
      'We met a farmer whose was very friendly.',
      'We met a farmer, whose lives in the glen.',
      'We met a farmer whose the sheepdog barked.'],
    a: 'We met a farmer whose sheepdog had won a medal.',
    hint: 'This word shows belonging, so the thing owned should follow it immediately.',
    ex: '"Whose" is a possessive relative pronoun and is followed straight away by the noun owned.' },

  { id: 'cl127', topic: 'clauses',
    q: 'Where should the commas go?\n\n"My trainers which cost a fortune fell apart in a week."',
    opts: ['After "trainers" and after "fortune"', 'After "trainers" only', 'After "fortune" only', 'After "apart" only'],
    a: 'After "trainers" and after "fortune"',
    hint: 'A clause of extra information is fenced off at both ends.',
    ex: '"Which cost a fortune" is extra information, so a comma is needed at each end of it.' },

  { id: 'cl128', topic: 'clauses',
    q: 'Which part of this sentence is the main clause?\n\n"Even though the glen was quiet, Aisha kept walking until darkness fell."',
    opts: ['Aisha kept walking', 'Even though the glen was quiet', 'until darkness fell', 'the glen was quiet'],
    a: 'Aisha kept walking',
    hint: 'Strip away every part that begins with a joining word and see what survives.',
    ex: 'With both subordinate clauses removed, "Aisha kept walking" still stands alone as a sentence.' },

  { id: 'cl129', topic: 'clauses',
    q: 'What type of sentence is this?\n\n"Because the tide was out, we crossed to the island and we picnicked on the sand."',
    opts: ['Compound-complex', 'Complex', 'Compound', 'Simple'],
    a: 'Compound-complex',
    hint: 'Check for BOTH two main clauses AND a subordinate clause.',
    ex: 'Two main clauses joined by "and" plus a subordinate clause beginning "Because" make it compound-complex.' },

  { id: 'cl130', topic: 'clauses',
    q: 'Which sentence uses its relative pronouns correctly?',
    opts: ['The pupils who visited the museum saw a skeleton which was 5,000 years old.',
      'The pupils which visited the museum saw a skeleton who was 5,000 years old.',
      'The pupils whose visited the museum saw a skeleton which was 5,000 years old.',
      'The pupils who visited the museum saw a skeleton whom was 5,000 years old.'],
    a: 'The pupils who visited the museum saw a skeleton which was 5,000 years old.',
    hint: '"Who" belongs with people and "which" belongs with things.',
    ex: 'The pupils are people, so they take "who"; the skeleton is a thing, so it takes "which".' },

  /* ── Active & passive voice ────────────────────────────────── */
  { id: 'pv101', topic: 'voice',
    q: 'Which sentence is in the PASSIVE voice?',
    opts: ['The window was cracked by a stray ball.',
      'A stray ball cracked the window.',
      'The ball rolled down the hill.',
      'Cracking windows is expensive.'],
    a: 'The window was cracked by a stray ball.',
    hint: 'In the passive, the subject has the action done to it.',
    ex: 'The subject "the window" receives the action, and the doer follows "by".' },

  { id: 'pv102', topic: 'voice',
    q: 'Which sentence is in the ACTIVE voice?',
    opts: ['Freya painted the shed.',
      'The shed was painted by Freya.',
      'The shed had been painted.',
      'The shed was being painted.'],
    a: 'Freya painted the shed.',
    hint: 'In the active voice the subject does the action.',
    ex: 'Freya is the subject and she does the painting, so the sentence is active.' },

  { id: 'pv103', topic: 'voice',
    // FIX: "sheep" is unchanged in the plural, so "was fed"/"were fed" were both
    // defensible depending on whether one or several sheep were meant — no single
    // correct answer. Swapped to "lambs", which has an unambiguous plural form.
    q: 'Rewrite in the passive voice:\n\n"Callum fed the lambs."',
    opts: ['The lambs were fed by Callum.',
      'The lambs was fed by Callum.',
      'Callum was fed by the lambs.',
      'The lambs have fed Callum.'],
    a: 'The lambs were fed by Callum.',
    hint: 'The object of the active sentence becomes the subject, and the verb takes a form of "to be".',
    ex: '"The lambs" becomes the plural subject, so the verb is "were fed" and the doer follows "by".' },

  { id: 'pv104', topic: 'voice',
    q: 'Rewrite in the active voice:\n\n"The trophy was presented by the head teacher."',
    opts: ['The head teacher presented the trophy.',
      'The trophy presented the head teacher.',
      'The trophy was given out by the head teacher.',
      'The head teacher was presented with the trophy.'],
    a: 'The head teacher presented the trophy.',
    hint: 'Move the doer to the front and let it own the verb.',
    ex: 'The agent "the head teacher" becomes the subject, so the verb turns into the plain active "presented".' },

  { id: 'pv105', topic: 'voice',
    q: 'Who or what is the agent in this sentence?\n\n"The path was blocked by fallen branches."',
    opts: ['fallen branches', 'the path', 'was blocked', 'by'],
    a: 'fallen branches',
    hint: 'The agent is whatever actually did the action.',
    ex: 'The branches did the blocking, and the phrase "by fallen branches" names them as the agent.' },

  { id: 'pv106', topic: 'voice',
    q: 'Which sentence hides who did the action?',
    opts: ['The window was smashed during the night.',
      'The window was smashed by a stray ball.',
      'A stray ball smashed the window.',
      'Someone smashed the window.'],
    a: 'The window was smashed during the night.',
    hint: 'An agentless passive simply leaves out the "by ..." part.',
    ex: 'There is no "by ..." phrase, so the reader is never told who smashed it.' },

  { id: 'pv107', topic: 'voice',
    q: 'Why would a scientist write "The mixture was heated to 60°C" instead of "I heated the mixture"?',
    opts: ['To keep the focus on the process rather than the person',
      'To make the report sound friendlier',
      'Because the passive is always shorter',
      'Because science reports must avoid the past tense'],
    a: 'To keep the focus on the process rather than the person',
    hint: 'Think about what a method section is really reporting.',
    ex: 'The passive puts the process first, which is what matters when someone repeats the experiment.' },

  { id: 'pv108', topic: 'voice',
    q: 'Choose the correct present-tense passive:\n\n"The ferry ___ every morning at eight."',
    opts: ['is cleaned', 'was cleaned', 'cleans', 'has cleaning'],
    a: 'is cleaned',
    hint: 'Match the tense to "every morning", then add the past participle.',
    ex: '"Is cleaned" is the present simple passive: the ferry has the cleaning done to it.' },

  { id: 'pv109', topic: 'voice',
    q: 'Choose the correct future passive:\n\n"The results ___ tomorrow morning."',
    opts: ['will be announced', 'will announce', 'are announcing', 'were announced'],
    a: 'will be announced',
    hint: 'The future passive needs three parts, and the middle one is "be".',
    ex: '"Will be announced" is will + be + past participle, and the results receive the action.' },

  { id: 'pv110', topic: 'voice',
    q: 'What tense is the passive verb in this sentence?\n\n"The bridge had been repaired before the storm arrived."',
    opts: ['Past perfect', 'Present perfect', 'Past simple', 'Future'],
    a: 'Past perfect',
    hint: '"Had" places the action further back than another past event.',
    ex: '"Had been repaired" is the past perfect passive, because the repair happened before the storm arrived.' },

  { id: 'pv111', topic: 'voice',
    q: 'Which sentence is in the passive voice?',
    opts: ['The tickets were sold in under an hour.',
      'The queue was enormous.',
      'The tickets sold out quickly.',
      'Selling tickets is hard work.'],
    a: 'The tickets were sold in under an hour.',
    hint: '"To be" plus a past participle signals the passive; "to be" plus an adjective does not.',
    ex: '"Were sold" is "to be" plus a past participle, so the tickets had the action done to them.' },

  { id: 'pv112', topic: 'voice',
    q: 'Rewrite in the passive voice, keeping the same tense:\n\n"The council is repairing the road."',
    opts: ['The road is being repaired by the council.',
      'The road was repaired by the council.',
      'The road is repaired by the council.',
      'The road has been repaired by the council.'],
    a: 'The road is being repaired by the council.',
    hint: 'An action still going on needs "is being" before the past participle.',
    ex: 'The present continuous passive "is being repaired" matches the tense of "is repairing".' },

  { id: 'pv113', topic: 'voice',
    q: 'A news report says: "A shop in Dundee was broken into last night."\n\nWhy has the reporter used the passive?',
    opts: ['The person responsible is not yet known',
      'To make the shop sound more important',
      'Because news reports never name places',
      'Because the passive makes every sentence shorter'],
    a: 'The person responsible is not yet known',
    hint: 'Ask what information the writer is missing.',
    ex: 'The passive lets the reporter describe the event without naming a doer nobody has identified.' },

  { id: 'pv114', topic: 'voice',
    q: 'Which word is the past participle in this passive sentence?\n\n"The photographs were taken by Rory."',
    opts: ['taken', 'were', 'photographs', 'Rory'],
    a: 'taken',
    hint: 'It is the part of the verb that could follow "have".',
    ex: '"Taken" is the past participle, and pairing it with "were" makes the verb passive.' },

  { id: 'pv115', topic: 'voice',
    q: 'What is the effect of the passive here?\n\n"Mistakes were made."',
    opts: ['It avoids saying who made the mistakes',
      'It makes clear exactly who is to blame',
      'It shifts the sentence into the future',
      'It turns the statement into a question'],
    a: 'It avoids saying who made the mistakes',
    hint: 'Notice what is missing from the end of the sentence.',
    ex: 'With no "by ..." phrase, the passive reports the mistakes while keeping the doer hidden.' },

  { id: 'pv116', topic: 'voice',
    q: 'Which sentence is in the ACTIVE voice?',
    opts: ['Aisha has written a poem about the loch.',
      'A poem about the loch has been written by Aisha.',
      'The poem was read aloud.',
      'The poem is being marked.'],
    a: 'Aisha has written a poem about the loch.',
    hint: 'Find the sentence whose subject is doing the action.',
    ex: 'Aisha is the subject and she does the writing, so the sentence is active.' },

  { id: 'pv117', topic: 'voice',
    q: 'Rewrite in the passive voice:\n\n"Someone has stolen my bike."',
    opts: ['My bike has been stolen.',
      'My bike was stealing.',
      'My bike has stolen.',
      'Someone has been stolen my bike.'],
    a: 'My bike has been stolen.',
    hint: 'The present perfect passive uses "has been" before the past participle.',
    ex: '"Has been stolen" keeps the same tense and lets the vague agent "someone" drop away.' },

  { id: 'pv118', topic: 'voice',
    q: 'When is the active voice usually the better choice?',
    opts: ['When you want writing to feel direct and lively',
      'When you want to hide who did something',
      'When you are listing the steps of a science method',
      'When the doer is completely unknown'],
    a: 'When you want writing to feel direct and lively',
    hint: 'Think about which voice names the doer straight away.',
    ex: 'Active voice puts the doer first, which keeps writing clear and energetic.' },

  { id: 'pv119', topic: 'voice',
    q: 'Rewrite in the passive voice:\n\n"A local artist designed the mural."',
    opts: ['The mural was designed by a local artist.',
      'The mural designed a local artist.',
      'The mural has designed by a local artist.',
      'A local artist was designed by the mural.'],
    a: 'The mural was designed by a local artist.',
    hint: 'Swap the doer and the receiver, then add a form of "to be".',
    ex: 'The mural receives the action, so it becomes the subject of "was designed", with the artist after "by".' },

  { id: 'pv120', topic: 'voice',
    q: 'Which phrase names the agent?\n\n"The trophy was won by Skye High School in June."',
    opts: ['by Skye High School', 'in June', 'The trophy', 'was won'],
    a: 'by Skye High School',
    hint: 'Not every phrase after the verb names a doer — some only tell you when.',
    ex: '"By Skye High School" names who did the winning, while "in June" only says when it happened.' },

  /* ── Clauses (second bank) ─────────────────────────────────── */
  { id: 'cl131', topic: 'clauses',
    q: 'Which part of this sentence is the subordinate clause?\n\n"We stayed indoors while the storm raged outside."',
    opts: ['while the storm raged outside', 'We stayed indoors', 'the storm raged', 'stayed indoors'],
    a: 'while the storm raged outside',
    hint: 'A subordinate clause starts with a joining word and cannot stand alone.',
    ex: '"While the storm raged outside" begins with "while", so it depends on the main clause.' },

  { id: 'cl132', topic: 'clauses',
    q: 'Identify the main clause:\n\n"Although she was nervous, Aisha stepped onto the stage."',
    opts: ['Aisha stepped onto the stage', 'Although she was nervous', 'she was nervous', 'onto the stage'],
    a: 'Aisha stepped onto the stage',
    hint: 'The main clause still makes sense with everything else removed.',
    ex: '"Aisha stepped onto the stage" stands alone as a complete sentence, so it is the main clause.' },

  { id: 'cl133', topic: 'clauses',
    q: 'Identify the subordinating conjunction:\n\n"Rory wore two jumpers because the bothy was freezing."',
    opts: ['because', 'and', 'two', 'wore'],
    a: 'because',
    hint: 'Look for the word that makes the second idea depend on the first.',
    ex: '"Because" introduces the subordinate clause "because the bothy was freezing".' },

  { id: 'cl134', topic: 'clauses',
    q: 'Choose the correct relative pronoun:\n\n"The runner ___ trained hardest won the medal."',
    opts: ['who', 'which', 'where', 'whose'],
    a: 'who',
    hint: 'The clause is about a person doing the action.',
    ex: '"Who" is the relative pronoun for a person acting as the subject.' },

  { id: 'cl135', topic: 'clauses',
    q: 'Choose the correct relative pronoun:\n\n"That is the café ___ we first met."',
    opts: ['where', 'which', 'who', 'whom'],
    a: 'where',
    hint: 'The clause tells you the place in which something happened.',
    ex: '"Where" links a relative clause to a place: the café where we met.' },

  { id: 'cl136', topic: 'clauses',
    q: 'Choose the correct relative pronoun:\n\n"Aisha, ___ won the poetry prize, is only eleven."',
    opts: ['who', 'which', 'whose', 'where'],
    a: 'who',
    hint: 'The commas show extra information about a person.',
    ex: '"Who" introduces a non-defining clause about a person.' },

  { id: 'cl137', topic: 'clauses',
    q: 'What type of sentence is this?\n\n"The kettle boiled and Freya made the tea."',
    opts: ['Compound', 'Simple', 'Complex', 'Compound-complex'],
    a: 'Compound',
    hint: 'Two main clauses joined by a coordinating conjunction.',
    ex: 'Two complete clauses joined by "and" make a compound sentence.' },

  { id: 'cl138', topic: 'clauses',
    q: 'What type of sentence is this?\n\n"We cancelled the walk because the path was flooded."',
    opts: ['Complex', 'Simple', 'Compound', 'Compound-complex'],
    a: 'Complex',
    hint: 'One clause here cannot stand on its own.',
    ex: 'A main clause plus a subordinate clause beginning "because" makes a complex sentence.' },

  { id: 'cl139', topic: 'clauses',
    q: 'What type of sentence is this?\n\n"The old lighthouse stood alone on the rocky headland."',
    opts: ['Simple', 'Compound', 'Complex', 'Compound-complex'],
    a: 'Simple',
    hint: 'Count the verbs, not the words.',
    ex: 'It is descriptive but has only one clause and one verb, so it is a simple sentence.' },

  { id: 'cl140', topic: 'clauses',
    q: 'Which part of this sentence is the embedded clause?\n\n"The bridge, which the flood had damaged, was closed."',
    opts: ['which the flood had damaged', 'The bridge was closed', 'was closed', 'the flood'],
    a: 'which the flood had damaged',
    hint: 'An embedded clause is dropped inside the main clause, often between commas.',
    ex: 'It sits inside "The bridge was closed" and is fenced off by a pair of commas.' },

  { id: 'cl141', topic: 'clauses',
    q: 'Which sentence contains a subordinate clause?',
    opts: ['Callum cheered when the whistle blew.',
      'Callum cheered and clapped loudly.',
      'Callum cheered at the final goal.',
      'Callum cheered for his team and waved.'],
    a: 'Callum cheered when the whistle blew.',
    hint: 'Look for a word such as when, because, although or if.',
    ex: '"When the whistle blew" cannot stand alone, so it is a subordinate clause.' },

  { id: 'cl142', topic: 'clauses',
    q: 'Is the relative clause defining or non-defining?\n\n"The pupil who scored the goal was cheered."',
    opts: ['Defining', 'Non-defining', 'Neither — it is a main clause', 'Neither — it is a phrase'],
    a: 'Defining',
    hint: 'Does the clause tell you which pupil, or just add extra detail?',
    ex: 'It has no commas and pins down which pupil is meant, so it is a defining relative clause.' },

  { id: 'cl143', topic: 'clauses',
    q: 'Where should the comma go?\n\n"Because the tide was rising we hurried back."',
    opts: ['after "rising"', 'after "Because"', 'after "tide"', 'after "back"'],
    a: 'after "rising"',
    hint: 'A subordinate clause at the front is closed off before the main clause starts.',
    ex: 'The fronted clause "Because the tide was rising" ends there, so the comma marks the join.' },

  { id: 'cl144', topic: 'clauses',
    q: 'Which word is NOT a subordinating conjunction?',
    opts: ['so', 'because', 'although', 'while'],
    a: 'so',
    hint: 'One of these links two clauses of equal weight.',
    ex: '"So" is a coordinating conjunction, joining two main clauses rather than subordinating one.' },

  { id: 'cl145', topic: 'clauses',
    q: 'How many clauses does this sentence contain?\n\n"If the rain stops, we will walk to the falls and take some photographs."',
    opts: ['Three', 'Two', 'Four', 'One'],
    a: 'Three',
    hint: 'Every clause has its own verb group — count them.',
    ex: 'The clauses are "If the rain stops", "we will walk to the falls" and "(we will) take some photographs".' },

  { id: 'cl146', topic: 'clauses',
    q: 'Choose the version with the subordinate clause moved to the front:\n\n"The team celebrated after they won the cup."',
    opts: ['After they won the cup, the team celebrated.',
      'After they won the cup the team celebrated.',
      'The team, after they won the cup celebrated.',
      'The team celebrated, after they won the cup.'],
    a: 'After they won the cup, the team celebrated.',
    hint: 'Fronting a subordinate clause changes the punctuation as well as the order.',
    ex: 'The subordinate clause comes first and a comma marks where the main clause begins.' },

  { id: 'cl147', topic: 'clauses',
    q: 'Which sentence is complex?',
    opts: ['Freya smiled because her plan had worked.',
      'Freya smiled and took a bow.',
      'Freya smiled at the audience.',
      'Freya smiled; the crowd cheered.'],
    a: 'Freya smiled because her plan had worked.',
    hint: 'A complex sentence needs a main clause and a subordinate clause.',
    ex: '"Because her plan had worked" is subordinate, so the whole sentence is complex.' },

  { id: 'cl148', topic: 'clauses',
    q: 'Choose the correct relative pronoun:\n\n"The tools ___ the builders used were very old."',
    opts: ['that', 'who', 'whom', 'whose'],
    a: 'that',
    hint: 'The clause is about things and tells you exactly which tools.',
    ex: '"That" introduces a defining relative clause about things.' },

  { id: 'cl149', topic: 'clauses',
    q: 'Which sentence uses "whose" correctly?',
    opts: ['We watched a diver whose bravery amazed us.',
      'We watched a diver whose was very brave.',
      'We watched a diver, whose swims every day.',
      'We watched a diver whose the medal shone.'],
    a: 'We watched a diver whose bravery amazed us.',
    hint: 'This word shows belonging, so the thing owned follows it immediately.',
    ex: '"Whose" is a possessive relative pronoun, followed straight away by the noun owned.' },

  { id: 'cl150', topic: 'clauses',
    q: 'Which part of this sentence is the main clause?\n\n"When the ferry docked, the passengers, who were exhausted, cheered."',
    opts: ['the passengers cheered', 'When the ferry docked', 'who were exhausted', 'the ferry docked'],
    a: 'the passengers cheered',
    hint: 'Strip away every part that begins with a joining word and see what survives.',
    ex: 'With both subordinate parts removed, "the passengers cheered" stands alone as a sentence.' },

  { id: 'cl151', topic: 'clauses',
    q: 'What type of sentence is this?\n\n"When the lights dimmed, the audience fell silent and the play began."',
    opts: ['Compound-complex', 'Complex', 'Compound', 'Simple'],
    a: 'Compound-complex',
    hint: 'Check for BOTH two main clauses AND a subordinate clause.',
    ex: 'Two main clauses joined by "and" plus a subordinate clause beginning "When" make it compound-complex.' },

  { id: 'cl152', topic: 'clauses',
    q: 'Identify the subordinating conjunction:\n\n"Unless the fog lifts, the flight will be delayed."',
    opts: ['Unless', 'will', 'the', 'lifts'],
    a: 'Unless',
    hint: 'Which word makes the first half unable to stand alone?',
    ex: '"Unless" introduces the subordinate clause "Unless the fog lifts".' },

  { id: 'cl153', topic: 'clauses',
    q: 'Choose the correctly punctuated sentence.\n\n(The writer has only one brother.)',
    opts: ['My brother, who lives in Perth, plays the pipes.',
      'My brother who lives in Perth, plays the pipes.',
      'My brother, who lives in Perth plays the pipes.',
      'My brother who lives in Perth plays the pipes.'],
    a: 'My brother, who lives in Perth, plays the pipes.',
    hint: 'If the clause is extra information, fence it off at both ends.',
    ex: 'With only one brother, the clause is extra information, so it needs a comma on each side.' },

  { id: 'cl154', topic: 'clauses',
    q: 'Which sentence is missing a pair of commas?',
    opts: ['My uncle who is a chef cooked the whole meal.',
      'The dog that chased the ball is ours.',
      'The parcel that arrived today is heavy.',
      'Anyone who is late will miss the bus.'],
    a: 'My uncle who is a chef cooked the whole meal.',
    hint: 'Only extra information needs commas; information that identifies does not.',
    ex: '"Who is a chef" is extra information about someone already identified, so it needs a comma at each end.' },

  { id: 'cl155', topic: 'clauses',
    q: 'Choose the correct relative pronoun:\n\n"The scientist ___ we interviewed studies whales."',
    opts: ['whom', 'which', 'whose', 'what'],
    a: 'whom',
    hint: 'The person is not doing the action — the person is being interviewed.',
    ex: '"Whom" is used when the person is the object of the verb: we interviewed her.' },

  { id: 'cl156', topic: 'clauses',
    q: 'How many clauses does this sentence contain?\n\n"The gulls cried overhead."',
    opts: ['One', 'Two', 'Three', 'Four'],
    a: 'One',
    hint: 'Count the verb groups.',
    ex: 'There is a single verb group, "cried", so the sentence has just one clause.' },

  { id: 'cl157', topic: 'clauses',
    q: 'Which sentence begins with a subordinate clause?',
    opts: ['As soon as the bell rang, the pupils rushed out.',
      'The pupils rushed out as soon as the bell rang.',
      'At the sound of the bell, the pupils rushed out.',
      'The pupils rushed out at the bell.'],
    a: 'As soon as the bell rang, the pupils rushed out.',
    hint: 'A clause has its own verb; a phrase does not.',
    ex: '"As soon as the bell rang" has its own verb and cannot stand alone, so it is a fronted subordinate clause.' },

  { id: 'cl158', topic: 'clauses',
    q: 'What job does the relative clause do here?\n\n"The trainers that I bought last week are already worn out."',
    opts: ['It tells you which trainers are meant',
      'It adds extra information you could remove',
      'It joins two main clauses',
      'It replaces the main verb'],
    a: 'It tells you which trainers are meant',
    hint: 'Try deleting the clause and see whether you still know which trainers.',
    ex: 'It is a defining relative clause: it pins down which trainers, which is why it takes no commas.' },

  { id: 'cl159', topic: 'clauses',
    q: 'Where should the commas go?\n\n"The castle which dates from 1400 attracts many visitors."',
    opts: ['After "castle" and after "1400"', 'After "castle" only', 'After "1400" only', 'After "visitors" only'],
    a: 'After "castle" and after "1400"',
    hint: 'A clause of extra information is fenced off at both ends.',
    ex: '"Which dates from 1400" is extra information, so a comma is needed at each end of it.' },

  { id: 'cl160', topic: 'clauses',
    q: 'Which sentence uses its relative pronouns correctly?',
    opts: ['The chef who cooked the meal used herbs that she had grown.',
      'The chef which cooked the meal used herbs who she had grown.',
      'The chef whose cooked the meal used herbs that she had grown.',
      'The chef who cooked the meal used herbs whom she had grown.'],
    a: 'The chef who cooked the meal used herbs that she had grown.',
    hint: '"Who" belongs with people and "that" or "which" belongs with things.',
    ex: 'The chef is a person, so she takes "who"; the herbs are things, so they take "that".' },

  /* ── Active & passive voice (second bank) ──────────────────── */
  { id: 'pv121', topic: 'voice',
    q: 'Which sentence is in the PASSIVE voice?',
    opts: ['The letter was posted this morning.',
      'The postman posted the letter.',
      'The letter arrived late.',
      'Posting letters is easy.'],
    a: 'The letter was posted this morning.',
    hint: 'In the passive, the subject has the action done to it.',
    ex: 'The subject "the letter" receives the action of being posted, so the sentence is passive.' },

  { id: 'pv122', topic: 'voice',
    q: 'Which sentence is in the ACTIVE voice?',
    opts: ['Rory baked the bread.',
      'The bread was baked by Rory.',
      'The bread had been baked.',
      'The bread was being baked.'],
    a: 'Rory baked the bread.',
    hint: 'In the active voice the subject does the action.',
    ex: 'Rory is the subject and he does the baking, so the sentence is active.' },

  { id: 'pv123', topic: 'voice',
    q: 'Rewrite in the passive voice:\n\n"The volunteers planted the trees."',
    opts: ['The trees were planted by the volunteers.',
      'The trees was planted by the volunteers.',
      'The volunteers were planted by the trees.',
      'The trees have planted the volunteers.'],
    a: 'The trees were planted by the volunteers.',
    hint: 'The object becomes the subject, and the verb takes a form of "to be".',
    ex: '"The trees" becomes the plural subject, so the verb is "were planted", with the doer after "by".' },

  { id: 'pv124', topic: 'voice',
    q: 'Rewrite in the active voice:\n\n"The medals were handed out by the mayor."',
    opts: ['The mayor handed out the medals.',
      'The medals handed out the mayor.',
      'The medals were given by the mayor.',
      'The mayor was handed the medals.'],
    a: 'The mayor handed out the medals.',
    hint: 'Move the doer to the front and let it own the verb.',
    ex: 'The agent "the mayor" becomes the subject, so the verb turns into the active "handed out".' },

  { id: 'pv125', topic: 'voice',
    q: 'Who or what is the agent in this sentence?\n\n"The crops were flattened by the gale."',
    opts: ['the gale', 'the crops', 'were flattened', 'by'],
    a: 'the gale',
    hint: 'The agent is whatever actually did the action.',
    ex: 'The gale did the flattening, and the phrase "by the gale" names it as the agent.' },

  { id: 'pv126', topic: 'voice',
    q: 'Which sentence hides who did the action?',
    opts: ['The rules were changed last term.',
      'The rules were changed by the head teacher.',
      'The head teacher changed the rules.',
      'Someone changed the rules.'],
    a: 'The rules were changed last term.',
    hint: 'An agentless passive simply leaves out the "by ..." part.',
    ex: 'There is no "by ..." phrase, so the reader is never told who changed the rules.' },

  { id: 'pv127', topic: 'voice',
    q: 'Choose the correct present-tense passive:\n\n"The recycling ___ every Thursday."',
    opts: ['is collected', 'was collected', 'collects', 'has collecting'],
    a: 'is collected',
    hint: 'Match the tense to "every Thursday", then add the past participle.',
    ex: '"Is collected" is the present simple passive: the recycling has the collecting done to it.' },

  { id: 'pv128', topic: 'voice',
    q: 'Choose the correct future passive:\n\n"The winners ___ at the assembly."',
    opts: ['will be named', 'will name', 'are naming', 'were named'],
    a: 'will be named',
    hint: 'The future passive needs will + be + past participle.',
    ex: '"Will be named" is will + be + past participle, and the winners receive the action.' },

  { id: 'pv129', topic: 'voice',
    q: 'What tense is the passive verb in this sentence?\n\n"The hall had been decorated before the guests arrived."',
    opts: ['Past perfect', 'Present perfect', 'Past simple', 'Future'],
    a: 'Past perfect',
    hint: '"Had" places the action further back than another past event.',
    ex: '"Had been decorated" is the past perfect passive, because it happened before the guests arrived.' },

  { id: 'pv130', topic: 'voice',
    q: 'Which sentence is in the passive voice?',
    opts: ['The bridge was painted last year.',
      'The bridge was enormous.',
      'The bridge stood for a century.',
      'Painting bridges is slow work.'],
    a: 'The bridge was painted last year.',
    hint: '"To be" plus a past participle signals the passive; "to be" plus an adjective does not.',
    ex: '"Was painted" is "to be" plus a past participle, so the bridge had the action done to it.' },

  { id: 'pv131', topic: 'voice',
    q: 'Rewrite in the passive voice, keeping the same tense:\n\n"The workers are building a new pier."',
    opts: ['A new pier is being built by the workers.',
      'A new pier was built by the workers.',
      'A new pier is built by the workers.',
      'A new pier has been built by the workers.'],
    a: 'A new pier is being built by the workers.',
    hint: 'An action still going on needs "is being" before the past participle.',
    ex: 'The present continuous passive "is being built" matches the tense of "are building".' },

  { id: 'pv132', topic: 'voice',
    q: 'Which word is the past participle in this passive sentence?\n\n"The song was written by a local band."',
    opts: ['written', 'was', 'song', 'band'],
    a: 'written',
    hint: 'It is the part of the verb that could follow "have".',
    ex: '"Written" is the past participle, and pairing it with "was" makes the verb passive.' },

  { id: 'pv133', topic: 'voice',
    q: 'A report states: "The fire alarm was set off at noon."\n\nWhy has the writer used the passive?',
    opts: ['Who set it off is not stated',
      'To make the alarm sound louder',
      'Because reports never give times',
      'Because the passive is always shorter'],
    a: 'Who set it off is not stated',
    hint: 'Ask what information the sentence leaves out.',
    ex: 'The passive lets the writer report the event without saying who set the alarm off.' },

  { id: 'pv134', topic: 'voice',
    q: 'What is the effect of the passive here?\n\n"The vase was broken."',
    opts: ['It avoids saying who broke the vase',
      'It makes clear exactly who is to blame',
      'It shifts the sentence into the future',
      'It turns the statement into a question'],
    a: 'It avoids saying who broke the vase',
    hint: 'Notice what is missing from the end of the sentence.',
    ex: 'With no "by ..." phrase, the passive reports the breakage while keeping the doer hidden.' },

  { id: 'pv135', topic: 'voice',
    q: 'Which sentence is in the ACTIVE voice?',
    opts: ['Euan has repaired the old clock.',
      'The old clock has been repaired by Euan.',
      'The clock was wound each night.',
      'The clock is being mended.'],
    a: 'Euan has repaired the old clock.',
    hint: 'Find the sentence whose subject is doing the action.',
    ex: 'Euan is the subject and he does the repairing, so the sentence is active.' },

  { id: 'pv136', topic: 'voice',
    q: 'Rewrite in the passive voice:\n\n"Someone has taken my umbrella."',
    opts: ['My umbrella has been taken.',
      'My umbrella was taking.',
      'My umbrella has taken.',
      'Someone has been taken my umbrella.'],
    a: 'My umbrella has been taken.',
    hint: 'The present perfect passive uses "has been" before the past participle.',
    ex: '"Has been taken" keeps the same tense and lets the vague agent "someone" drop away.' },

  { id: 'pv137', topic: 'voice',
    q: 'When is the passive voice often the better choice?',
    opts: ['When the doer is unknown or unimportant',
      'When you want the writing to feel lively',
      'When you want to name the doer first',
      'When you are writing a personal diary'],
    a: 'When the doer is unknown or unimportant',
    hint: 'Think about the sentences where no one is named after "by".',
    ex: 'The passive is useful when who did the action is unknown or does not matter.' },

  { id: 'pv138', topic: 'voice',
    q: 'Rewrite in the passive voice:\n\n"A famous poet opened the festival."',
    opts: ['The festival was opened by a famous poet.',
      'The festival opened a famous poet.',
      'The festival has opened by a famous poet.',
      'A famous poet was opened by the festival.'],
    a: 'The festival was opened by a famous poet.',
    hint: 'Swap the doer and the receiver, then add a form of "to be".',
    ex: 'The festival receives the action, so it becomes the subject of "was opened", with the poet after "by".' },

  { id: 'pv139', topic: 'voice',
    q: 'Which phrase names the agent?\n\n"The record was broken by a young swimmer in July."',
    opts: ['by a young swimmer', 'in July', 'The record', 'was broken'],
    a: 'by a young swimmer',
    hint: 'Not every phrase after the verb names a doer — some only tell you when.',
    ex: '"By a young swimmer" names who did the breaking, while "in July" only says when.' },

  { id: 'pv140', topic: 'voice',
    q: 'What tense is the passive verb in this sentence?\n\n"The gates are locked at dusk each day."',
    opts: ['Present simple', 'Past simple', 'Future', 'Past perfect'],
    a: 'Present simple',
    hint: '"Each day" tells you this is a regular, present habit.',
    ex: '"Are locked" is the present simple passive, describing something that happens every day.' },
];

export const CLAUSE_VOICE_ITEM_COUNT = CLAUSE_VOICE_ITEMS.length;
