/**
 * Spelling — extra word bank for P7 / S1 (ages 11–13).
 *
 * Same shape and tone as spelling.js: [word, clue sentence containing the word,
 * the rule it teaches]. The app blanks the word out of the clue automatically,
 * so every clue contains its word exactly once, as a whole word.
 *
 * UK English throughout (practise/practice, licence/license, -ise, -our, -re).
 */

export const EXTRA_SPELLING = {
  'homophones': [
    ['license', 'The council will license the new taxi rank next month.', 'license = the verb (s = do it)'],
    ['device', 'He invented a clever device for opening stiff jars.', 'device = the noun (like "ice")'],
    ['devise', 'Can you devise a plan for the summer fair?', 'devise = the verb (like "ise")'],
    ['weather', 'The forecast warned of stormy weather all weekend.', 'weather = sun, rain and wind'],
    ['whether', 'I cannot decide whether to go or stay.', 'whether = if, a choice'],
    ['aloud', 'She read the poem aloud to the whole class.', 'aloud = out loud, so others hear'],
    ['allowed', 'Mobile phones are not allowed in the exam hall.', 'allowed = permitted'],
    ['bought', 'He bought a new pair of boots with his birthday money.', 'bought = paid for something'],
    ['brought', 'She brought her cousin along to the party.', 'brought = carried it with you'],
    ['quiet', 'The library was completely quiet.', 'quiet = silent (qui-ET)'],
    ['quite', 'The last question was quite difficult.', 'quite = fairly, rather'],
    ['desert', 'Camels can cross the hot, dry desert.', 'desert = sand, one s'],
    ['dessert', 'We had ice cream for dessert.', 'dessert = sweet, so two s'],
    ['compliment', 'She paid him a lovely compliment about his artwork.', 'compliment = praise (I like it)'],
    ['complement', 'That scarf is a perfect complement to her coat.', 'complement = completes it'],
    ['draught', 'A cold draught came in under the door.', 'draught = a current of cold air'],
    ['alter', 'The tailor will alter the sleeves to make them shorter.', 'alter = to change'],
    ['coarse', 'The sand on that beach is rough and coarse.', 'coarse = rough (it has "oar")'],
    ['course', 'She signed up for a cookery course.', 'course = lessons, or a route'],
    ['herd', 'A herd of cattle blocked the narrow road.', 'herd = a group of animals'],
    ['peace', 'After the argument the two friends made peace.', 'peace = calm, no fighting'],
    ['piece', 'Would you like a piece of cake?', 'piece = a part (a piece of pie)'],
    ['brake', 'Press the brake to slow the bike down.', 'brake = what stops a vehicle'],
    ['threw', 'He threw the ball over the fence.', 'threw = past tense of throw'],
    ['guest', 'Every guest was given a name badge at the door.', 'guest = a visitor'],
    ['loose', 'The handle on the door has come loose.', 'loose = not tight (double o)'],
    ['lose', 'Try not to lose your locker key.', 'lose = to mislay (one o)'],
    ['cereal', 'He ate a bowl of cereal for breakfast.', 'cereal = breakfast grain'],
    ['weight', 'The scales showed the weight of the parcel.', 'weight = how heavy it is'],
    ['medal', 'She won a gold medal in the relay.', 'medal = a prize you wear'],
    ['plain', 'He wore a plain white shirt with no pattern.', 'plain = simple, undecorated'],
    ['steel', 'The bridge is built from concrete and steel.', 'steel = the strong metal'],
    ['site', 'Builders fenced off the construction site.', 'site = a place or plot of land'],
    ['led', 'The guide led us along the cliff path.', 'led = past tense of lead'],
    ['too', 'The bag was far too heavy to lift.', 'too = also, or excessively'],
    ['two', 'She bought two tickets for the concert.', 'two = the number 2'],
    ['here', 'Please come here and sit beside me.', 'here = this place'],
    ['hear', 'Can you hear the pipes playing in the distance?', 'hear = to listen (it has "ear")'],
    ['knew', 'She knew the answer straight away.', 'knew = past tense of know'],
    ['wear', 'You must wear a helmet when cycling.', 'wear = to put clothes on'],
    ['where', 'Do you know where the hall is?', 'where = in which place'],
    ['meat', 'The butcher sold fresh meat every morning.', 'meat = food from animals'],
    ['meet', 'Let us meet outside the cinema at six.', 'meet = to come together'],
    ['sea', 'The boat sailed far out to sea.', 'sea = the ocean'],
    ['flour', 'Add the flour slowly to the mixing bowl.', 'flour = ground wheat for baking'],
    ['flower', 'She picked a single flower from the garden.', 'flower = a bloom on a plant'],
    ['break', 'Be careful not to break the window.', 'break = to snap or shatter'],
    ['sight', 'The castle was a magnificent sight at sunset.', 'sight = something seen'],
    ['write', 'Remember to write your name at the top.', 'write = to form letters'],
    ['right', 'Turn right at the end of the road.', 'right = correct, or opposite of left'],
    ['week', 'We have a spelling test every week.', 'week = seven days'],
    ['weak', 'After the illness he still felt weak.', 'weak = not strong'],
    ['mail', 'The parcel arrived in the morning mail.', 'mail = post, letters'],
    ['male', 'A male blackbird has a bright orange beak.', 'male = a boy or man'],
    ['tail', 'The dog wagged its tail with excitement.', 'tail = the back end of an animal'],
    ['tale', 'Grandad told us a tale about the sea.', 'tale = a story'],
    ['hare', 'A brown hare darted across the field.', 'hare = a fast animal like a rabbit'],
    ['bare', 'The trees were bare in the middle of winter.', 'bare = uncovered, empty'],
    ['bear', 'A polar bear lives in the frozen north.', 'bear = a large wild animal'],
    ['whole', 'She ate the whole apple in one go.', 'whole = complete, all of it'],
    ['hole', 'The rabbit vanished down a hole.', 'hole = a hollow or gap'],
    ['son', 'The farmer taught his son to drive the tractor.', 'son = a male child'],
    ['sun', 'The sun rose slowly over the hills.', 'sun = the star in our sky'],
    ['won', 'Our team won the final match.', 'won = past tense of win'],
    ['your', 'Is this your coat on the peg?', 'your = belonging to you'],
    ['you\'re', 'I hope you\'re feeling better today.', "you're = you are"],
    ['its', 'The cat licked its paws clean.', 'its = belonging to it (no apostrophe)'],
    ['it\'s', 'I think it\'s going to rain soon.', "it's = it is"],
    ['fair', 'We went on the rides at the summer fair.', 'fair = a funfair, or just and even'],
    ['fare', 'The bus fare went up in April.', 'fare = the cost of a journey'],
    ['steal', 'It is wrong to steal from other people.', 'steal = to take without permission'],
    ['groan', 'He let out a groan when he saw the homework.', 'groan = a low moaning sound'],
    ['grown', 'The sunflower has grown taller than me.', 'grown = past participle of grow'],
    ['waist', 'The apron was tied around her waist.', 'waist = the middle of the body'],
    ['waste', 'Do not waste paper when you sketch.', 'waste = to use carelessly, or rubbish'],
  ],
  'ible-able': [
    ['horrible', 'The smell from the blocked drain was horrible.', 'Root is not a full word → -ible'],
    ['edible', 'Check that the berries are edible before eating them.', 'Root is not a full word → -ible'],
    ['legible', 'Her handwriting was neat and legible.', 'Root is not a full word → -ible'],
    ['flexible', 'Gymnasts need to be extremely flexible.', 'Latin root flex- → -ible'],
    ['audible', 'His whisper was barely audible at the back.', 'Latin audi = hear → -ible'],
    ['eligible', 'You are eligible to enter if you are under thirteen.', 'The -ible keeps the g soft'],
    ['accessible', 'The new entrance is accessible to wheelchair users.', 'Root ends in -ss → -ible'],
    ['invisible', 'The ink stayed invisible until it was heated.', 'Root is not a full word → -ible'],
    ['compatible', 'This charger is not compatible with my phone.', 'Root is not a full word → -ible'],
    ['permissible', 'Talking is not permissible during the test.', 'Root ends in -miss → -ible'],
    ['plausible', 'He gave a plausible excuse for being late.', 'Root is not a full word → -ible'],
    ['invincible', 'The champion seemed invincible until the final round.', 'The -ible keeps the c soft'],
    ['adorable', 'The puppies in the basket were adorable.', 'Root "adore" is a word → -able'],
    ['believable', 'Her acting was completely believable.', 'Root "believe" is a word → -able'],
    ['breakable', 'Wrap the breakable items in bubble wrap.', 'Root "break" is a full word → -able'],
    ['changeable', 'Scottish weather is famously changeable.', 'Keep the e to keep the g soft'],
    ['fashionable', 'Those trainers are very fashionable this year.', 'Root "fashion" is a word → -able'],
    ['memorable', 'The trip to Skye was truly memorable.', 'Root "memory" → -able'],
    ['miserable', 'Cold, wet socks made him miserable.', 'Root "misery" → -able'],
    ['noticeable', 'There was a noticeable improvement in his work.', 'Keep the e to keep the c soft'],
    ['portable', 'She carried a small portable speaker in her bag.', 'Latin port = carry → -able'],
    ['predictable', 'The ending of the film was rather predictable.', 'Root "predict" is a word → -able'],
    ['remarkable', 'It was a remarkable effort for a first attempt.', 'Root "remark" is a word → -able'],
    ['suitable', 'Choose footwear suitable for a long hill walk.', 'Root "suit" is a full word → -able'],
    ['understandable', 'His nerves before the concert were understandable.', 'Root "understand" is a word → -able'],
  ],
  'ant-ent': [
    ['excellent', 'Her report said her effort this term was excellent.', '-ent, like "different"'],
    ['apparent', 'It soon became apparent that we were lost.', '-ent after "appar"'],
    ['permanent', 'The fall left a permanent scar on his knee.', '-ent, not -ant'],
    ['frequent', 'There are frequent buses into town on Saturdays.', '-ent, not -ant'],
    ['consistent', 'She has been consistent in her training all season.', '-ent, not -ant'],
    ['magnificent', 'The castle looked magnificent in the low sunlight.', '-ent after a soft c'],
    ['intelligent', 'Crows are surprisingly intelligent birds.', '-ent, not -ant'],
    ['innocent', 'The jury found the accused man innocent.', '-ent after a soft c'],
    ['competent', 'He is a competent swimmer but not a fast one.', '-ent, not -ant'],
    ['brilliant', 'The fireworks over the harbour were brilliant.', '-ant: brilli-ANT'],
    ['constant', 'The constant noise from the roadworks was annoying.', '-ant, not -ent'],
    ['elegant', 'She wore an elegant blue dress to the ceilidh.', '-ant, not -ent'],
    ['ignorant', 'I was completely ignorant of the new rules.', '-ant, not -ent'],
    ['observant', 'An observant pupil spotted the mistake on the board.', '-ant, not -ent'],
    ['pleasant', 'We had a pleasant walk along the river.', '-ant: pleas-ANT'],
    ['hesitant', 'He was hesitant to answer in front of everyone.', '-ant, not -ent'],
    ['confidence', 'Winning the race gave her real confidence.', '-ence, matching -ent'],
    ['evidence', 'The detective searched the room for evidence.', '-ence, not -ance'],
    ['silence', 'A minute of silence was held before the match.', '-ence, not -ance'],
    ['influence', 'Adverts can influence what we choose to buy.', '-ence, not -ance'],
    ['distance', 'The distance from Perth to Inverness is over a hundred miles.', '-ance, matching -ant'],
    ['guidance', 'Ask your teacher for guidance on the project.', '-ance, not -ence'],
    ['substance', 'The scientist tested the unknown white substance.', '-ance, not -ence'],
    ['nuisance', 'The wasps at the picnic were a real nuisance.', '-ance, not -ence'],
    ['ambulance', 'An ambulance rushed the patient to hospital.', '-ance, not -ence'],
  ],
  'silent-double': [
    ['knight', 'The knight rode into battle wearing heavy armour.', 'Silent k and silent gh'],
    ['wrestle', 'The two cubs began to wrestle in the long grass.', 'Silent w and silent t'],
    ['doubt', 'I have no doubt that she will pass.', 'Silent b — think of "dubious"'],
    ['debt', 'He worked all summer to pay off his debt.', 'Silent b — think of "debit"'],
    ['subtle', 'There was a subtle difference between the two shades.', 'Silent b'],
    ['whistle', 'The referee blew his whistle to end the game.', 'Silent t'],
    ['column', 'The temple roof rested on a stone column.', 'Silent n at the end'],
    ['autumn', 'The leaves turn golden in autumn.', 'Silent n at the end'],
    ['solemn', 'The remembrance service was quiet and solemn.', 'Silent n at the end'],
    ['muscle', 'He pulled a muscle during the sprint.', 'Silent c — think of "muscular"'],
    ['scene', 'The final scene of the play was dramatic.', 'Silent c after the s'],
    ['scent', 'The dog followed the scent through the woods.', 'Silent c after the s'],
    ['foreign', 'Learning a foreign language takes practice.', 'Silent g before the n'],
    ['sword', 'The museum displayed a rusted Viking sword.', 'Silent w'],
    ['answer', 'Write your answer in the box below.', 'Silent w'],
    ['salmon', 'A salmon leapt right up the waterfall.', 'Silent l'],
    ['receipt', 'Keep the receipt in case you need a refund.', 'Silent p; e before i after c'],
    ['plumber', 'The plumber fixed the leaking pipe under the sink.', 'Silent b'],
    ['castle', 'We climbed the steps to the ruined castle.', 'Silent t'],
    ['thistle', 'The thistle is the emblem of Scotland.', 'Silent t'],
    ['address', 'Write your address clearly on the envelope.', 'Two d, two s'],
    ['aggressive', 'The player was booked for aggressive behaviour.', 'Two g, two s'],
    ['immediately', 'Stop what you are doing and come here immediately.', 'Two m — immediate + ly'],
    ['occasion', 'A wedding is a very special occasion.', 'Two c, one s'],
    ['possession', 'The ball was in our possession for most of the match.', 'Two s, then two s again'],
    ['succeed', 'If you keep trying, you will succeed.', 'Two c, two e'],
    ['suggest', 'Can you suggest a good book to read?', 'Two g'],
    ['tomorrow', 'The trip has been moved to tomorrow.', 'One m, two r'],
    ['across', 'They rowed all the way across the loch.', 'One c, two s'],
    ['professional', 'She hopes to become a professional dancer.', 'One f, two s'],
    ['exaggerate', 'Do not exaggerate — the fish was not that big.', 'Two g'],
    ['accidentally', 'He accidentally knocked over the paint pot.', 'Two c, two l: accidental + ly'],
  ],
  'roots': [
    ['telephone', 'She picked up the telephone and dialled the number.', 'tele = far, phone = sound'],
    ['microphone', 'Speak into the microphone so everyone can hear.', 'micro = small, phone = sound'],
    ['photosynthesis', 'Plants make food from sunlight by photosynthesis.', 'photo = light, synthesis = putting together'],
    ['biography', 'He read a biography of Robert Burns.', 'bio = life, graph = writing'],
    ['autobiography', 'The singer wrote an autobiography about her own life.', 'auto = self, bio = life, graph = writing'],
    ['automatic', 'The doors open by an automatic sensor.', 'auto = self, so it acts by itself'],
    ['democracy', 'In a democracy the people vote for their leaders.', 'demos = people, kratos = rule'],
    ['geology', 'In geology we studied rocks and volcanoes.', 'geo = earth, ology = study of'],
    ['geometry', 'In geometry we measured angles and shapes.', 'geo = earth, metron = measure'],
    ['aquarium', 'We watched the sharks at the aquarium.', 'aqua = water'],
    ['aquatic', 'Frogs and newts are aquatic creatures.', 'aqua = water'],
    ['dictionary', 'Look the unfamiliar word up in a dictionary.', 'dict = say or speak'],
    ['predict', 'Scientists still cannot predict earthquakes.', 'pre = before, dict = say'],
    ['inspect', 'An engineer came to inspect the old bridge.', 'in = into, spect = look'],
    ['construct', 'The class had to construct a model bridge from straws.', 'con = together, struct = build'],
    ['circumference', 'Measure the circumference of the circle with string.', 'circum = around, ferre = carry'],
    ['century', 'The castle was built in the fifteenth century.', 'cent = hundred'],
    ['decade', 'Ten years make one decade.', 'deca = ten'],
    ['triangle', 'A triangle has three straight sides.', 'tri = three, angle = corner'],
    ['bicycle', 'He rode his bicycle all the way to school.', 'bi = two, cycle = wheel'],
    ['astronaut', 'The astronaut floated inside the space station.', 'astro = star, nautes = sailor'],
    ['sympathy', 'She wrote a card to show her sympathy.', 'sym = together, pathos = feeling'],
    ['telegraph', 'Before phones, messages were sent by telegraph.', 'tele = far, graph = writing'],
    ['signature', 'The letter ended with the head teacher signature.', 'signum = a mark or sign'],
    ['annual', 'The school holds an annual sports day each June.', 'annus = year, so once a year'],
  ],
  'tricky': [
    ['neighbour', 'Our next-door neighbour looks after our cat.', 'UK keeps the u; "eigh" as in eight'],
    ['recognise', 'I did not recognise him with his new haircut.', 'UK uses -ise; keep the silent g'],
    ['organise', 'They will organise the charity sale together.', 'UK uses -ise, not -ize'],
    ['programme', 'The concert programme listed every song.', 'UK: programme for a show or plan'],
    ['theatre', 'We watched the play at the theatre in Perth.', 'UK ends in -re, not -er'],
    ['colour', 'Green is a very calming colour.', 'UK keeps the u'],
    ['travelled', 'They travelled to Orkney by ferry.', 'UK doubles the l before -ed'],
    ['calendar', 'Mark the date of the trip on the calendar.', 'Ends in -ar, not -er'],
    ['business', 'Her mum runs a small baking business.', 'busi-ness, from "busy" (y to i)'],
    ['library', 'He borrowed three books from the library.', 'Two r sounds: li-BRA-ry'],
    ['height', 'The nurse measured his height and weight.', 'Ends -ght, like light'],
    ['grateful', 'She was grateful for all their help.', 'From "grate", not "great"'],
    ['especially', 'I love fruit, especially raspberries.', 'especial + ly, so two l'],
    ['opportunity', 'This is a great opportunity to learn Gaelic.', 'Two p, one r'],
    ['argument', 'They had a short argument about the rules.', '"Argue" loses its e before -ment'],
    ['similar', 'The twins wore similar jackets.', 'Ends in -ar, not -er'],
    ['temperature', 'The temperature dropped below freezing overnight.', 'Say tem-per-a-ture to hear every part'],
    ['secretary', 'The club secretary took notes at the meeting.', 'A secretary keeps a secret'],
    ['jewellery', 'She kept her jewellery in a wooden box.', 'UK: jewel + lery, two l'],
    ['government', 'The Scottish government meets at Holyrood.', 'Govern + ment, keep the n'],
    ['environment', 'Plastic waste damages the environment.', 'Environ + ment, keep the n'],
    ['marvellous', 'The view from the summit was marvellous.', 'UK doubles the l: marvel + lous'],
    ['mischievous', 'The mischievous kitten unravelled the wool.', 'mis-chie-vous, no i before -ous'],
    ['familiar', 'His face looked oddly familiar.', 'Ends in -iar, not -ier'],
    ['privilege', 'It is a privilege to represent your school.', 'No d: privi-lege'],
  ],
};
